In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.keras as keras
import tensorflow  as tf

In [2]:
frame = pd.read_csv(r'weekcount.csv')
df = pd.DataFrame(frame)
df =pd.get_dummies(df, prefix=['station' ])

#reading and dumming datta
col = list(df.columns.values)

df = df[['year', 'week', 'station_5 Corners Library', 'station_Astor Place', 'station_Baldwin at Montgomery', 'station_Bayside Park', 'station_Bergen Ave', 'station_Bethune Center', 'station_Brunswick & 6th', 'station_Brunswick St', 'station_Central Ave', 'station_Christ Hospital', 'station_City Hall', 'station_Columbia Park', 'station_Columbus Dr at Exchange Pl', 'station_Columbus Drive', 'station_Communipaw & Berry Lane', 'station_Danforth Light Rail', 'station_Dey St', 'station_Dixon Mills', 'station_Essex Light Rail', 'station_Exchange Place', 'station_Fairmount Ave', 'station_Garfield Ave Station', 'station_Glenwood Ave', 'station_Grand St', 'station_Grove St PATH', 'station_Hamilton Park', 'station_Harborside', 'station_Heights Elevator', 'station_Hilltop', 'station_Hoboken Ave at Monmouth St', 'station_JC Medical Center', 'station_JCBS Depot', 'station_Jackson Square', 'station_Jersey & 3rd', 'station_Jersey & 6th St', 'station_Journal Square', 'station_Lafayette Park', 'station_Leonard Gordon Park', 'station_Liberty Light Rail', 'station_Lincoln Park', 'station_MLK Light Rail', 'station_Manila & 1st', 'station_Marin Light Rail', 'station_McGinley Square', 'station_Monmouth and 6th', 'station_Montgomery St', 'station_Morris Canal', 'station_NJCU', 'station_Newark Ave', 'station_Newport PATH', 'station_Newport Pkwy', 'station_North St', 'station_Oakland Ave', 'station_Paulus Hook', 'station_Pershing Field', 'station_Riverview Park', 'station_Sip Ave', 'station_Union St', 'station_Van Vorst Park', 'station_Warren St', 'station_Washington St', 'station_West Side Light Rail', 'station_York St', 'anzahl']]



print(col)
print(df)


['year', 'week', 'anzahl', 'station_5 Corners Library', 'station_Astor Place', 'station_Baldwin at Montgomery', 'station_Bayside Park', 'station_Bergen Ave', 'station_Bethune Center', 'station_Brunswick & 6th', 'station_Brunswick St', 'station_Central Ave', 'station_Christ Hospital', 'station_City Hall', 'station_Columbia Park', 'station_Columbus Dr at Exchange Pl', 'station_Columbus Drive', 'station_Communipaw & Berry Lane', 'station_Danforth Light Rail', 'station_Dey St', 'station_Dixon Mills', 'station_Essex Light Rail', 'station_Exchange Place', 'station_Fairmount Ave', 'station_Garfield Ave Station', 'station_Glenwood Ave', 'station_Grand St', 'station_Grove St PATH', 'station_Hamilton Park', 'station_Harborside', 'station_Heights Elevator', 'station_Hilltop', 'station_Hoboken Ave at Monmouth St', 'station_JC Medical Center', 'station_JCBS Depot', 'station_Jackson Square', 'station_Jersey & 3rd', 'station_Jersey & 6th St', 'station_Journal Square', 'station_Lafayette Park', 'stati

In [3]:
wframe = pd.read_csv(r'weather.csv')
weather = pd.DataFrame(wframe)
weather.head()

year  week  sunHour  totalSnow_cm  FeelsLikeC  cloudcover  humidity  \
0  2015    39    10.00           0.0       18.57       37.86     66.00   
1  2015    40     8.57           0.0       14.86       69.29     82.14   
2  2015    41     9.31           0.0       16.29       25.00     71.57   
3  2015    42     8.70           0.0       12.29       17.00     65.57   
4  2015    43     7.81           0.0       12.29       27.29     68.00   

   precipMM  tempC  windspeedKmph  
0      0.00  21.86          13.57  
1      4.73  18.14          22.43  
2      0.71  19.57          11.71  
3      0.07  16.29          15.71  
4      0.56  16.57          16.29

In [4]:
df = pd.merge(df,weather,on=['year','week'],how='outer').dropna()
df.head()

year  week  station_5 Corners Library  station_Astor Place  \
0  2015    39                        1.0                  0.0   
1  2015    39                        0.0                  0.0   
2  2015    39                        0.0                  0.0   
3  2015    39                        0.0                  0.0   
4  2015    39                        0.0                  0.0   

   station_Baldwin at Montgomery  station_Bayside Park  station_Bergen Ave  \
0                            0.0                   0.0                 0.0   
1                            1.0                   0.0                 0.0   
2                            0.0                   1.0                 0.0   
3                            0.0                   0.0                 0.0   
4                            0.0                   0.0                 0.0   

   station_Bethune Center  station_Brunswick & 6th  station_Brunswick St  ...  \
0                     0.0                      0.0                   0.0  ...   
1                     0.0                      0.0                   0.0  ...   
2                     0.0                      0.0                   0.0  ...   
3                     0.0                      0.0                   1.0  ...   
4                     0.0                      0.0                   0.0  ...   

   station_York St  anzahl  sunHour  totalSnow_cm  FeelsLikeC  cloudcover  \
0              0.0    43.0     10.0           0.0       18.57       37.86   
1              0.0    66.0     10.0           0.0       18.57       37.86   
2              0.0    16.0     10.0           0.0       18.57       37.86   
3              0.0   186.0     10.0           0.0       18.57       37.86   
4              0.0    25.0     10.0           0.0       18.57       37.86   

   humidity  precipMM  tempC  windspeedKmph  
0      66.0       0.0  21.86          13.57  
1      66.0       0.0  21.86          13.57  
2      66.0       0.0  21.86          13.57  
3      66.0       0.0  21.86          13.57  
4      66.0       0.0  21.86          13.57  

[5 rows x 74 columns]

In [ ]:
df['anzahl'].describe()

In [ ]:
print(tf.__version__)
from tensorflow.python.client import device_lib
def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]
print(get_available_devices()) 

In [ ]:
#loadmodel
with tf.device('/device:GPU:0'):
    model = keras.models.load_model('kimodelweather')

In [5]:

x = df.iloc[:,0:-1].values
y = df.iloc[:,65:66].values
print(x)
print(y[21])


[[2.015e+03 3.900e+01 1.000e+00 ... 6.600e+01 0.000e+00 2.186e+01]
 [2.015e+03 3.900e+01 0.000e+00 ... 6.600e+01 0.000e+00 2.186e+01]
 [2.015e+03 3.900e+01 0.000e+00 ... 6.600e+01 0.000e+00 2.186e+01]
 ...
 [2.020e+03 4.400e+01 0.000e+00 ... 6.657e+01 6.210e+00 1.386e+01]
 [2.020e+03 4.400e+01 0.000e+00 ... 6.657e+01 6.210e+00 1.386e+01]
 [2.020e+03 4.400e+01 0.000e+00 ... 6.657e+01 6.210e+00 1.386e+01]]
[17.]


In [6]:
#x_train, x_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.15,shuffle=False )

split_horizontally_idx = int(x.shape[0]* 0.8)
x_train = x[:split_horizontally_idx , :]
x_test = x[split_horizontally_idx: , :]
y_train = y[:split_horizontally_idx , :]
y_test = y[split_horizontally_idx: , :]
print(x_train.shape); print(y_test.shape)
tf.debugging.set_log_device_placement(True)

(10170, 73)
(2543, 1)


In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Layer
model = keras.models.Sequential()
 
    
model.add(keras.layers.Dense(81, kernel_initializer='normal',  activation='relu', input_shape=(81,) ))
model.add(Dense(81, kernel_initializer='normal',activation='relu'))
model.add(Dense(81, kernel_initializer='normal',activation='relu'))
model.add(Dense(81, kernel_initializer='normal',activation='relu'))
model.add(Dense(81, kernel_initializer='normal',activation='relu'))
model.add(Dense(1, kernel_initializer='normal',activation='linear'))
model.add(Dense(1))



Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomStandardNormal in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device

In [8]:

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.0001), loss='mae', metrics=[tf.keras.metrics.MeanAbsolutePercentageError()])

Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhos

In [ ]:
with tf.device('/device:GPU:0'):
    print(tf.device)
    model.fit(x_train, y_train, epochs=200 ,batch_size=10, shuffle=True)

In [ ]:
# print("Evaluate on test data")
with tf.device('/device:GPU:0'):
    results = model.evaluate(x_test, y_test )
print("test loss, test acc:", results)


In [ ]:
test_data = x_train[21]
print (test_data)
with tf.device('/device:GPU:0'):
    print(model.predict(test_data.reshape(1,65), batch_size=1))
print(y_train[21])

In [ ]:
print("Generate predictions for 3 samples")
print(x_train[1000:1020])
with tf.device('/device:GPU:0'):
    predictions = model.predict(x_train[1000:1020])
print("predictions shape:",( predictions))
print(y_train[1000:1020])

In [ ]:
print("Generate predictions for 3 samples")
print(x_test)
with tf.device('/device:GPU:0'):
    predictions = model.predict(x_test)
print("predictions shape:",( predictions))
print(y_test)

In [ ]:
#save model
model.save('kimodelweather')